# Generated by Django 5.0.2 on 2024-04-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_users_alter_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
    ]
